{application, canvas,
 [{description, "Canvas Server"},
  {vsn, "0.01"},
  {modules, [
    canvas,
    canvas_app,
    canvas_deps,
    canvas_sup,
    canvas_web,
    client_list,
    client_mailbox,
    client_manager,
    line_store,
    request_controller,
    spatial,
    util
  ]},
  {registered, []},
  {mod, {canvas_app, []}},
  {env, []},
  {applications, [kernel, stdlib, crypto]}]}.
